### ISSUE TITLE
Is there an easy way to allow unsupported/deprecated ciphers?

### ISSUE THREAD

**Issue by RIPv1** [evilsocket/shellz#1]
**What version of Go are you using (go version)?**

go1.11 darwin/amd64

**What operating system and processor architecture are you using (go env)?**

MacOS 10.14 

**What did you do?**

Attempting connection to ssh host

**What did you expect to see?**

Successful authentication

**What did you see instead?**

ssh: no common algorithm for client to server cipher; client offered: [aes128-gcm@openssh.com chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr], server offered: [aes128-cbc aes256-cbc]

**Comment by RIPv1** [comment]
This is not an issue, as its working as expected. Just wondering if its possible to enable deprecated ciphers as 90% of my routers/switches only support it. Thanks for this awesome utility!

**Comment by evilsocket** [comment]
Done, you can specify your ciphers like this:

```json
{
    "name": "old-server",
    "host": "old.server",
    "port": 22,
    "identity": "default",
    "ciphers": ["aes128-cbc", "3des-cbc"]
}
```
