### ISSUE TITLE
Follow XDG Base Directory Specification (avoid dotfiles in home folder)

### ISSUE THREAD

**Issue by AnimiVulpis** [evilsocket/shellz#14]
_Could be seen as an extension of #8 "Custom configurations support"_

I think it would be a good idea to follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)
which is already in use by a lot of other tools and reduces cluttering the home (`~/`) folder.

What do you think, what is your stance on this?

**Comment by evilsocket** [comment]
i'm a ~/dotfiles old-schooler :)
