### ISSUE TITLE
Password protected private keys

### ISSUE THREAD

**Issue by MAGICCC** [evilsocket/shellz#5]
Hi, 
I just wanted to try shellz, but it seems we can't use password protected private keys. 
`error while creating session for shell hetzner-magic: error while parsing key file /home/magic/.ssh/id_rsa: ssh: can not decode encrypted private keys `

**Comment by MAGICCC** [comment]
Maybe you can interact with a kee agent

**Comment by evilsocket** [comment]
mmmm interesting, need to do some research. Thanks for the feedback and the idea! :D

**Comment by evilsocket** [comment]
fixed by https://github.com/evilsocket/shellz/commit/12cc1a539be7991e29a6c989c06a5acc796c0f8e
