### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by djerfy** [evilsocket/shellz#9]
Possible to support access IPv6, currently error:
```
war error while creating session for shell server1: dial tcp: address xxxx:xxxx:xxxx:xxxx::x:22: too many colons in address
war error while creating session for shell server2: dial tcp: address xxxx:xxxx:xxxx:xxxx::x:22: too many colons in address
war error while creating session for shell server3: dial tcp: address xxxx:xxxx:xxxx:xxxx::x:22: too many colons in address
```

I force access in IPv4 but it would be great for the addition. Thx

**Comment by evilsocket** [comment]
As per [doc](https://golang.org/pkg/net/#Dial), what if in the JSON file, you change:

```json
...
"host": "the-ipv6"
...
```
to
```json
...
"host": "[the-ipv6]"
...
```
?

**Comment by djerfy** [comment]
Yes it works with that but I use DNS directly (resolv IPv4 or IPv6)

**Comment by evilsocket** [comment]
what? i didn't understand, what's in your .json file, the ipv6 address or an hostname that resolves to an ipv6 address?

**Comment by djerfy** [comment]
an hostname that resolves to an ipv4/ipv6

**Comment by evilsocket** [comment]
mmm investigating

**Comment by evilsocket** [comment]
it seems a weird behaviour of go itself, check here https://twitter.com/evilsocket/status/1049624146529972224

**Comment by evilsocket** [comment]
@djerfy did you map that hostname to an ipv6 `link-local` address?

**Comment by djerfy** [comment]
> @djerfy did you map that hostname to an ipv6 `link-local` address?

no not an link-local but on a public ipv6

**Comment by evilsocket** [comment]
@djerfy would you compile form sources (README helps) and test if this commit fixed the issue?

**Comment by djerfy** [comment]
> @djerfy would you compile form sources (README helps) and test if this commit fixed the issue?

yes it's good for me 👍 (verified via tcpdump)

**Comment by evilsocket** [comment]
@djerfy there's something it's not clear to me, i double checked and this commit should *not* have fixed your specific issue, is there any `:` character in the hostname you're using?

**Comment by djerfy** [comment]
> @djerfy there's something it's not clear to me, i double checked and this commit should _not_ have fixed your specific issue, is there any `:` character in the hostname you're using?

no just `-` but it does not trouble

**Comment by evilsocket** [comment]
so i don't understand how the fix solved your issue ... if there's no `:`, `net.JoinHostPort` is equivalent to the `fmt.Sprintf` i was using ...

![schermata da 2018-10-09 15-01-32](https://user-images.githubusercontent.com/86922/46671818-132dab00-cbd6-11e8-9803-371cf7580301.png)
